rust-num/num-traits

src/lib.rs
Basically it is a copy of the stdlib implementation, should close #2
=> Implement std::fmt::Display for ParseFloatError

src/cast.rs
This is my personal attempt at #7. It is fairly similar to what can be found in `asprim`, although implemented from scratch. Please let me know of what you think. Could it use more tests? Should I also leave a safety notice that some conversions with `as` are currently UB (rust-lang/rust#10184)?
=> Add AsPrimitive trait for generic casting with `as`

src/int.rs, src/ops/checked.rs
Add traits `CheckedShl` and `CheckedShr` that correspond to the standard
library's `checked_shl` and `checked_shr` functions. Implement the trait
on all primitive integer types by default, akin to what the standard
library does.
The stdlib is somewhat inconsistent when it comes to the type of the
shift amount. The `checked_*` functions have a `u32` shift amount, but
the `std::ops::{Shl,Shr}` traits are generic over the shift amount. Also
the stdlib implements these traits for all primitive integer types as
right-hand sides. Our implementation mimics this behaviour.
=> Add checked shifts

src/lib.rs, src/real.rs, src/realnum.rs
This is supposed to fix [#19](https://github.com/rust-num/num-traits/issues/19); I assumed going ahead would be better than bumping the thread.  
In any case, I understand that it is a quite significant addition and won't mind too much if it doesn't make it.
This adds a new `RealNum` trait, along with a universal impl `impl<T: Float> RealNum for T { ... }`.  
Therefore, this shouldn't be a breaking change, except in places where both traits are imported (which obviously only happened in a few places in this crate).
The intent is that generic code may prefer to use `RealNum` instead of `Float` when floating-point isn't a requirement. In the future (next major version ?), I guess `Float` could be made to only provide floating-point-specific features on top of `RealNum`.
Most of the code+doc …
=> Add RealNum trait for real data types (Float, but without floating-point specific features)

Cargo.toml, README.md, ci/test_full.sh, src/bounds.rs, src/cast.rs, src/float.rs, src/identities.rs, src/int.rs, src/lib.rs, src/ops/checked.rs, src/ops/wrapping.rs, src/pow.rs, src/real.rs, src/sign.rs
This is a port of @vks's rust-num/num#296, but without the feature-toggled changes to `Float`.  Now `Float` and the newer `Real` are completely dependent on having `std` enabled.  In the future we can consider adding separate more-limited float/real traits that can work without `std`, like the `BaseFloat` that was originally proposed in the former PR.
This is a breaking change with a bump to 0.2, since anyone currently using `default-features = false` will lose functionality.  The actual API is otherwise unchanged, so my plan is to employ the "semver trick" -- publishing a new num-traits-0.1 that re-exports everything from 0.2 (with `std`).  Thus all `num-traits` users should remain compatible even if they mix 0.1 and 0.2.
Closes #16.
=> Re-introduce the std feature

README.md, src/cast.rs, src/float.rs, src/lib.rs, src/sign.rs
This is a subset of the `Float` trait, but works with `no_std`.
Some code was simplified by using `CoreFloat`.
=> Implement CoreFloat trait

src/identities.rs
Implements the version recommended in #5. That issue should remain open to track the breaking-change version.
=> Add is_one.

src/cast.rs, src/float.rs, src/lib.rs, src/macros.rs, src/real.rs, src/sign.rs
- New macros simplify forwarding method implementations.
- `Float` and `Real` use this to compact their implementations.
- `FloatCore` now forwards `std` implementations when possible.
- `FloatCore` now requires `NumCast`, like `Float does.
- New additions to `FloatCore`:
- Constants like `min_value()` -> `f64::MIN`
- Rounding methods `floor`, `ceil`, `round`, `trunc`, `fract`
- `integer_decode` matching `Float`'s
- Fix NAN sign handling in `FloatCore` (rust-num/num#312, rust-lang/rust#42425)
- Fix overflow in `FloatCore::powi` exponent negation.
- Add doctests to all `FloatCore` methods.
=> Various improvements to FloatCore

src/cast.rs
This is a rebase and continuation of PR #28.  The primary benefit is that
floats finally check for overflow before casting to integers, avoiding
undefined behavior.  Fixes #12.
The inter-integer conversions and all of the macros for these have also been
tweaked, hopefully improving readability.  Exhaustive tests have been added for
good and bad conversions around the target MIN and MAX values.
=> Refactor ToPrimitive range checks

src/lib.rs, src/ops/mod.rs, src/ops/mul_add.rs
Both `f32` and `f64` implement fused multiply-add, which computes `(self * a) + b` with only one rounding error. This produces a more accurate result with better performance than a separate multiplication operation followed by an add:
```rust
fn mul_add(self, a: f32, b: f32) -> f32[src]
```
It is however not possible to make use of this in a generic context by abstracting over a trait.
My concrete use-case is machine learning, [gradient descent](https://en.wikipedia.org/wiki/Gradient_descent) to be specific,  
where the core operation of updating the gradient could make use of `mul_add` for both its `weights: Vector` as well as its `bias: f32`:
```rust
struct Perceptron {
weights: Vector,
bias: f32,
}
impl MulAdd<f32, Self> for Vector {
// ...
}
impl Perceptron {
fn learn(&mut self, …
```
=> Added `MulAdd` and `MulAddAssign` traits

src/float.rs
The current `f32::to_degrees` implementation uses a division to
calculate 180/π, which causes a loss of precision. Using a constant is
still not perfect (implementing a maximally-precise algorithm would come
with a high performance cost), but improves precision with a minimal
change.
This is a backport from [`std`].
[`std`]: https://github.com/rust-lang/rust/pull/47919/commits/e34c31bf02eb0f0ff4dd43ae72e0eae53f2ac519
=> Use constant for 180/π in f32::to_degrees

Cargo.toml, RELEASES.md, src/cast.rs, tests/cast.rs
Particularly, the default `from_f64` used `n as i64`, which has
undefined behavior on overflow, kind of defeating the purpose here.
Now we use a checked `to_i64()` for this, and even try `to_u64()` as a
fallback for completeness.
Also make similar changes to default `ToPrimitive`, but at least it
didn't have the same casting problem.
=> Avoid `as` casts in default FromPrimitive methods

src/pow.rs
=> Updated documentation to note the pow(0, 0) case.

src/lib.rs, src/ops/wrapping.rs
Add traits `WrappingShl` and `WrappingShr` corresponding to the
standard library `wrapping_shl` and `wrapping_shr` methods. Implement
the trait on all primitive integer types as well as on `Wrapping`.
=> Add wrapping shifts

src/ops/checked.rs
Fix #57 and more:
- CheckedShl was hinting that None was returned on overflow rather than
on too large a rhs.
- Ditto for CheckedShr.
- CheckedShr documentation erroneously indicated that a left shift was
going to be performed instead of a right shift.
=> Fix CheckedShl/CheckedShr documentation

src/identities.rs
Adds the following default implemented methods to `Zero` and `One`:
```rust
fn set_zero(&mut self) {
*self = Zero::zero();
}
```
```rust
fn set_one(&mut self) {
*self = One::one();
}
```
This allows for reuse of BigNums.
=> Add inplace methods to `Zero` and `One`

src/int.rs
This documents the PrimInt trait, explains its intentions and features
as well as mentions its origins for future reference.
Closes #11.
=> int: document PrimInt trait

src/lib.rs
Ensure that splitting the potential sign character from the remainder
respects UTF8 boundaries. This lets invalid characters fail correctly
with an error, instead of panicking.
Closes: #125
=> Fix num parsing for invalid multi-byte sign chars

src/lib.rs
`NAN` preserving lower- and upper-clamp.
Cc: https://github.com/rust-ndarray/ndarray/issues/470#issuecomment-521809782
=> NAN preserving clamp_lower/upper

src/lib.rs
This also improves the docs for `clamp`, `clamp_min`, and `clamp_max`.
Closes #134.
=> Debug-panic in clamp_min/max if min/max is NAN

.travis.yml, Cargo.toml, README.md, ci/test_full.sh, src/float.rs, src/lib.rs, src/ops/mul_add.rs, src/pow.rs, src/real.rs
Greetings,
This is a hopeful fix for #75.  
Basically: Add `libm` as an optional dependency, and handle three possible cases depending on which features are enabled:
- std and libm: std is used;
- std and not libm: std is used;
- libm and not std: libm and FloatCore are used.
It was briefly mentioned that `libm` wasn't ready yet, but this was months ago, and I believe it is better not to wait for too long.  
If anything, bugs in `libm` should be fixed in `libm`; `num-traits` is only delegating its implementations to it; not to mention that the more `libm` is used, the likelier issues are to be found and hopefully fixed.
Thanks in advance!
=> Revive Float+Real in no_std thanks to libm

src/cast.rs
Closes #9 .
The added comments are pretty succinct, not going into details of the conversion (for example, truncation when converting from float to int). If something is missing, I'm not adverse to adding precision.
=> Document NumCast / ToPrimitive's sucess vs error rules

src/float.rs
Since it is not (yet?) added to the standard library, the value is included in the source here, instead of referring to a constant in `core`.
=> Add the full circle constant τ (TAU)

src/float.rs
=> Fix the parameter name in the FloatCore::max example

src/lib.rs, src/ops/wrapping.rs
Closes #10 
A quick search turned up that the [extprim](https://github.com/kennytm/extprim) implements `PrimInt` for its `u128` and `i128`, but, since both have their own `wrapping_neg` method, it's a non-issue.
That being said, I don't know for certain that it is the only project that implements `PrimInt`, so it might be wise to wait for a larger version bump before merging this.
=> Add WrappingNeg trait

src/float.rs
These correspond to the `extra_log_consts` added in Rust 1.43.
=> Add FloatConst::{LOG10_2, LOG2_10}

src/int.rs, src/lib.rs, src/ops/saturating.rs
Hi all,
Taking the suggestion from #40, this pull request breaks out the saturating trait into three separate SaturatingAdd, SaturatingSub and SaturatingMul traits, borrowing the idea from Checked* and Wrapping*. In terms of native ops, SaturatingNeg would be an option on signed types once the saturating_neg() API is stable on signed integer primitives.
I know there is concern about breaking changes, so I was thinking that I could add a wrapping Saturating trait for backwards compatibility that retains the original functionality:
```
pub trait Saturating: SaturatingAdd + SaturatingSub {}
impl<T> Saturating for T where T: SaturatingAdd + SaturatingSub {}
```
This is not included in the current version, but I would be happy to add.
-Tom (trepetti@cs.columbia.edu)
=> Add saturating_mul() and refactor Saturating into subtraits. Fixes #40.

src/cast.rs
Resolves #175.
Document the traits `ToPrimitive`, `FromPrimitive` and `NumCast` that
value can be represented by the target type
when they are within the range admitted by the target type,
and so truncation or precision loss may happen.
One question worth reflecting on is whether this documentation be normalized somewhere at module level,
and whether it should be replicated to all methods or simply stay at each trait.
I would also be open to adding examples with doctests if deemed useful.
=> Document cast traits about possible precision loss and truncation

src/cast.rs
Fixes #174
The safety section should not be removed entirely since people might be using older compilers (as was pointed out to me in a [related issue](https://github.com/yoanlcq/vek/issues/59) in the vek crate).
However, [this](https://github.com/rust-lang/rust/issues/15536#issuecomment-377681267) and followup comments indicate that the second case (float to float) was never UB in the first place - should the second example be removed?
=> Update AsPrimitive Safety docs for rust 1.45

src/ops/mod.rs, src/ops/overflowing.rs
Closes issue #168
I've been inspired by `saturated.rs`
=> Add Overflowing trait

src/cast.rs, tests/cast.rs
The implementation of `<f64 as ToPrimitive>::to_f32` was written at a
time when float-to-float overflow was though to be undefined behavior,
per rust-lang/rust#15536, but this was later determined to be fine.
Casting a large `f64` to `f32` just results in an infinity with the
matching sign. The sign gives more information than if `to_f32` just
returns `None`, so now we let these infinities through as a result.
See also rust-num/num-bigint#163 and rust-num/num-rational#83.
=> Allow large f64-to-f32 to saturate to infinity

build.rs
If the "i128" feature is explicity requested, don't bother probing for
it. It will still cause a build error if that was set improperly.
=> Trust the "i128" feature

src/lib.rs
Fixes #198.
While at it, also make parsing of the `"-NaN"` string match the standard library.
=> Use standard library for float from_str_radix with radix 10

src/bounds.rs
Potential solution for #208. With a breaking change, these could simply become supertraits of `Bounded`, but until then, we have to deal with blanket implementations.
I added both simply because it was easy to do so, although we could opt to not require both. I don't see it being that negative to include both, however.
=> Add LowerBounded/UpperBounded traits

build.rs, src/int.rs
Since this was only stabilised in 1.46.0, it falls back to a naïve version on older versions.
It seems unlikely that the version in libstd will ever be different from calling the zeros versions on !self, but for future-proofing, this defers to the libstd versions anyway.
=> Add leading_ones and trailing_ones to PrimInt

src/lib.rs
This copies some of the standard library fixes of <https://github.com/rust-lang/rust/pull/78618>.
=> Ignore case for float parsing of text special values

src/float.rs
[rust-gpu](/EmbarkStudios/rust-gpu) project uses num-traits directly and via glam. However, integer_decode() function is a bit poisonous for it - it immediately requires both Int16 and Int64 capabilities.
This PR reimplements corresponding functions in terms of libm's copysign. (For some reason, rust's libm is missing signbit - it can be done with a bitcast though, maybe that's actually a better implementation avenue).
=> Implement is_sign_* and signum methods in terms of bitcasts.

build.rs, src/lib.rs, src/ops/euclid.rs, src/ops/mod.rs
Fixes #159 
Add support for euclidean division and modulation.
=> Add support for euclidean division and modulation

Cargo.toml, build.rs, src/float.rs
=> Add copysign

tests/cast.rs
The cast tests generate some code with branches that contain min/max
operations that would overflow if they were reachable. Recent rustc
changes have gotten more aggressive with const-propagation, causing that
code to trigger the deny-by-default `arithmetic_overflow` lint, but we
can explicitly allow it in this case.
=> Allow `arithmetic_overflow` lint in a cast test

src/ops/mul_add.rs
There is some great documentation on the `MulAdd` trait itself, but in cases where you only see the method doc (like hovering in an IDE), it's not clear what operation will take place.
Sometimes I remember what role each of the three numbers has, and even where the parens are, but either way it breaks my concentration having to drill into the impl to find the trait doc to double-check my assumptions.
Short of copy-pasting the excellent `MulAdd` trait doc everywhere, I think that just including the pseudocode describing the operation (as I've done in this PR) will go a long way in clarifying what it does.
=> Clarify `mul_add` Docs

.github/workflows/ci.yaml, bors.toml, build.rs, ci/rustup.sh, src/float.rs
This is a rebase of #265, adding a default impl and an autocfg check.
Closes #264.
=> Add FloatCore and Float::is_subnormal

src/identities.rs
Fixes https://github.com/rust-num/num-traits/issues/285 .
From what I have seen, the local output generated with `cargo +nightly doc --open` (rustc v1.74.0 nightly 203c57dbe) does not look differently than the most current one found here: https://docs.rs/num-traits/latest/num_traits/identities/trait.One.html
Propably related to https://github.com/rust-lang/rust/pull/110800 ? If it is, then the issue might be fixed soon and this PR should be ignored..
=> Bugfix for text codeblock in documentation.

src/ops/euclid.rs
=> feat: add an extra method to (Checked)Euclid trait to get both quotien and rem

.github/workflows/ci.yaml, bors.toml, build.rs, ci/rustup.sh, src/float.rs, src/lib.rs
Define an orthogonal trait which corresponds to the `totalOrder` predicate the IEEE 754 (2008 revision) floating point standard.
In order to maintain coherence, the bounds on `TotalOrder` should most likely be `TotalOrder: Float` (or `TotalOrder: FloatCore`).  Without type constraints, `TotalOrder` could be defined on, well, anything. Though slightly ugly, one way to deal with this is to define two traits, `TotalOrderCore: FloatCore` and `TotalOrder: Float`.  On the other hand, `Inv` has no such constraints (due to the possibility of a meaningful implementation on rational numbers). If the crate designers could weigh in on whether to introduce constraints, that would be helpful.
Resolves: [issue#256](https://github.com/rust-num/num-traits/issues/256)
=> `TotalOrder` trait for floating point numbers

src/identities.rs, src/lib.rs
Adds traits which are alternatives to the more dynamic `Zero`/`One` traits which are useful for stack-allocated types where it's possible to define constant values for zero/one.
~~`ZeroConstant`~~ `ConstZero` bounds on `Zero` as a supertrait, and ~~`OneConstant`~~ `ConstOne` on `One`, allowing them to be used as drop-in replacements.
~~When a type also impls `PartialEq`, then `ZeroConstant` also provides a blanket impl of `Zero`, and likewise for `OneConstant`/`One`, making it simple for stack-allocated integers to impl these traits as an alternative to `Zero`/`One` while still remaining fully compatible.~~ (Edit: removed)
~~The internal impls of `Zero`/`One` on the numeric primitive types have been changed to use these traits, which should be a fully backwards-compatible change.~~ (Edit: …
=> Add `ConstZero` and `ConstOne` traits

.github/workflows/ci.yaml, .github/workflows/master.yaml, .github/workflows/pr.yaml, Cargo.toml, README.md, build.rs, ci/rustup.sh, ci/test_full.sh, src/cast.rs, src/float.rs, src/int.rs, src/lib.rs, src/ops/bytes.rs, src/ops/euclid.rs
Earlier versions won't see the incompatible updates at all!
=> Use namespaced-features to safely bump to MSRV 1.60

src/float.rs
Implementing `clamp` for Float per this issue: https://github.com/rust-num/num-traits/issues/234
=> Implementing clamp for Float trait

src/float.rs
Fixes https://github.com/rust-lang/rust/issues/126610
The example for trait method [float::Float::integer_decode](https://docs.rs/num-traits/0.2.19/num_traits/float/trait.Float.html#tymethod.integer_decode) fails if `num` is changed to most any value other than 2.
```rs
use num_traits::Float;
let num = 2.0f32;
// (8388608, -22, 1)
let (mantissa, exponent, sign) = Float::integer_decode(num);
let sign_f = sign as f32;
let mantissa_f = mantissa as f32;
let exponent_f = num.powf(exponent as f32);
// 1 * 8388608 * 2^(-22) == 2
let abs_difference = (sign_f * mantissa_f * exponent_f - num).abs();
assert!(abs_difference < 1e-10);
```
* The equation used to recover the original number, `num`, from the outputs of `Float::integer_decode(num)` is given in the doc comment as `sign * mantissa * 2 ^ …
=> Clarify example for trait method `float::Float::integer_decode`
